version: 2
default: &default
  working_directory: ~/{{CIRCLE_PROJECT_REPONAME}}
  docker:
    - image: circleci/node:6.10.3

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build Project
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
            - dist

  test:
    <<: *default
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Unit test & coverage test
          command: yarn test
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          filters:
            branches:
              only: /^((v[0-9]+(\.[0-9]+)*)|(master))$/
      - test:
          requires:
            - build
          filters:
            branches:
              only: /^v[0-9]+(\.[0-9]+)*$/
